name: 'Setup Pipeline URL'
description: 'Constructs the Bitbucket pipeline URL from workspace, repo slug, and pipeline UUID'

inputs:
  workspace:
    description: 'Bitbucket workspace name'
    required: true
  repo_slug:
    description: 'Bitbucket repository slug'
    required: true
  uuid:
    description: 'Pipeline UUID (with or without curly braces)'
    required: true

outputs:
  pipeline_url:
    description: 'URL to view the pipeline in Bitbucket dashboard'
    value: ${{ steps.setup.outputs.pipeline_url }}

runs:
  using: 'composite'
  steps:
    - name: Setup Pipeline URL
      id: setup
      shell: bash
      run: |
        # Use the reusable script to construct the pipeline URL
        # This ensures consistency across all uses of pipeline URL construction
        PIPELINE_URL=$(bash "${{ github.action_path }}/setup-pipeline-url.sh" "${{ inputs.workspace }}" "${{ inputs.repo_slug }}" "${{ inputs.uuid }}")
        
        # Output the URL
        echo "pipeline_url=${PIPELINE_URL}" >> $GITHUB_OUTPUT
        echo "Pipeline URL: ${PIPELINE_URL}"

