name: 'Wait for Bitbucket Pipeline by UUID'
description: 'Polls Bitbucket API to wait for a specific pipeline (by UUID) to complete'

inputs:
  bitbucket_api_token:
    description: 'Bitbucket API token with repository read permissions'
    required: true
  bitbucket_repo:
    description: 'Bitbucket repository in workspace/repo-slug format'
    required: true
  pipeline_uuid:
    description: 'UUID of the pipeline to wait for (with or without curly braces)'
    required: true
  poll_interval:
    description: 'Seconds between polling attempts (default: 120)'
    required: false
    default: '120'
  max_attempts:
    description: 'Maximum polling attempts before timeout (default: 15)'
    required: false
    default: '15'

outputs:
  pipeline_state:
    description: 'Final state of the pipeline (e.g., COMPLETED)'
    value: ${{ steps.wait.outputs.pipeline_state }}
  pipeline_result:
    description: 'Final result of the pipeline (e.g., SUCCESSFUL, FAILED, TIMEOUT)'
    value: ${{ steps.wait.outputs.pipeline_result }}
  pipeline_url:
    description: 'URL to view the pipeline in Bitbucket dashboard'
    value: ${{ steps.wait.outputs.pipeline_url }}

runs:
  using: 'composite'
  steps:
    - name: Wait for Bitbucket pipeline by UUID
      id: wait
      shell: bash
      env:
        BITBUCKET_API_TOKEN: ${{ inputs.bitbucket_api_token }}
        BITBUCKET_REPO: ${{ inputs.bitbucket_repo }}
        PIPELINE_UUID: ${{ inputs.pipeline_uuid }}
        POLL_INTERVAL: ${{ inputs.poll_interval }}
        MAX_ATTEMPTS: ${{ inputs.max_attempts }}
      run: node ${{ github.action_path }}/dist/index.js

